[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = []
optimizer = true
optimizer_runs = 20000
solc_version = "0.8.21"
evm_version = "paris"
via_ir = true

# See more config options https://github.com/gakonst/foundry/tree/master/config

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }